AZURE_OPENAI_KEY= '8J6pTdfaGgA5r193UVLsBshUspqwNpal42Jse1aHaok1cWNTLpRkJQQJ99BDACYeBjFXJ3w3AAABACOGLa23'
AZURE_OPENAI_ENDPOINT=  'https://ai-bcds.openai.azure.com/'
AZURE_OPENAI_DEPLOYMENT_NAME= 'gpt-4o-mini-BCwDS'
